title: Leo Duan
description: Statistician · Associate Professor, University of Florida
markdown: kramdown

nav:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Teaching
    url: /teaching/
  - title: Students
    url: /students/
  - title: Service
    url: /service/

exclude:
  - _layout
  - _include
  - scripts
  - "Leo Duan TP 2024-25.pdf"
